Description: >
  High-Availability Deployment Configuration.

Parameters:

  ENV:
    Description: Environment name.
    Type: String

  VpcCidr:
    Description: IP range (CIDR notation) for this VPC.
    Type: String
    Default: 10.0.0.0/16

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ENV}-VPC
